### ISSUE TITLE
Error while running the app demo on latest version of flutter 

### ISSUE THREAD

**Issue by mayur-novus** [matthew-carroll/flutter_ui_challenge_tinder_matching#1]
When trying to drag on the card, that does not work. Gives an error as below

```
I/flutter (10858): Desired slide direction SlideDirection.right
E/flutter (10858): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (10858): Cannot get size during build.
E/flutter (10858): The size of this render object has not yet been determined because the framework is still in the process of building widgets, which means the render tree for this frame has not yet been determined. The size getter should only be called from paint callbacks or interaction event handlers (e.g. gesture callbacks).
E/flutter (10858): 
E/flutter (10858): If you need some sizing information during build to decide which widgets to build, consider using a LayoutBuilder widget, which can tell you the layout constraints at a given location in the tree. See <https://docs.flutter.io/flutter/widgets/LayoutBuilder-class.html> for more details.
E/flutter (10858): 
E/flutter (10858): The size getter was called for the following element:
E/flutter (10858):   DraggableCard(dirty, state: _DraggableCardState#7ddcd(tickers: tracking 2 tickers))
E/flutter (10858): 
E/flutter (10858): #0      Element.size.<anonymous closure> (package:flutter/src/widgets/framework.dart:3109:9)
E/flutter (10858): #1      Element.size (package:flutter/src/widgets/framework.dart:3128:6)
E/flutter (10858): #2      _DraggableCardState._slideRight (package:prototype/cards.dart:297:33)
E/flutter (10858): <asynchronous suspension>
E/flutter (10858): #3      _DraggableCardState.didUpdateWidget (package:prototype/cards.dart:264:11)
E/flutter (10858): #4      StatefulElement.update (package:flutter/src/widgets/framework.dart:3797:58)
E/flutter (10858): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
E/flutter (10858): #6      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4392:32)
E/flutter (10858): #7      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4782:17)
E/flutter (10858): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
E/flutter (10858): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
E/flutter (10858): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
E/flutter (10858): #11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
E/flutter (10858): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
E/flutter (10858): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
E/flutter (10858): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
E/flutter (10858): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
E/flutter (10858): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
E/flutter (10858): #17     _invoke (dart:ui/hooks.dart:120:13)
E/flutter (10858): #18     _drawFrame (dart:ui/hooks.dart:109:3)
E/flutter (10858): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (10858): setState() or markNeedsBuild() called during build.
E/flutter (10858): This _OverlayEntry widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
E/flutter (10858): The widget on which setState() or markNeedsBuild() was called was:
E/flutter (10858):   _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#03c20](state: _OverlayEntryState#d4c06)
E/flutter (10858): The widget which was currently being built when the offending call was made was:
E/flutter (10858):   OverlayBuilder(dirty, state: _OverlayBuilderState#26086)
E/flutter (10858): #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3449:11)
E/flutter (10858): #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3475:6)
E/flutter (10858): #2      State.setState (package:flutter/src/widgets/framework.dart:1141:14)
E/flutter (10858): #3      _OverlayEntryState._markNeedsBuild (package:flutter/src/widgets/overlay.dart:174:5)
E/flutter (10858): #4      OverlayEntry.markNeedsBuild (package:flutter/src/widgets/overlay.dart:149:24)
E/flutter (10858): #5      _OverlayBuilderState.buildOverlay (package:fluttery/src/layout_overlays.dart:158:19)
E/flutter (10858): <asynchronous suspension>
E/flutter (10858): #6      _OverlayBuilderState.build (package:fluttery/src/layout_overlays.dart:163:5)
E/flutter (10858): #7      StatefulElement.build (package:flutter/src/widgets/framework.dart:3743:27)
E/flutter (10858): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3655:15)
E/flutter (10858): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
E/flutter (10858): #10     StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
E/flutter (10858): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
E/flutter (10858): #12     _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:118:18)
E/flutter (10858): #13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2235:19)
E/flutter (10858): #14     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:107:11)
E/flutter (10858): #15     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1666:58)
E/flutter (10858): #16     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:735:15)
E/flutter (10858): #17     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1666:13)
E/flutter (10858): #18     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:205:5)
E/flutter (10858): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
E/flutter (10858): #20     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
E/flutter (10858): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
E/flutter (10858): #22     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
E/flutter (10858): #23     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:338:7)
E/flutter (10858): #24     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
E/flutter (10858): #25     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
E/flutter (10858): #26     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
E/flutter (10858): #27     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:704:18)
E/flutter (10858): #28     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
E/flutter (10858): #29     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
E/flutter (10858): #30     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/render
E/flutter (10858): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (10858): setState() or markNeedsBuild() called during build.
E/flutter (10858): This _OverlayEntry widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
E/flutter (10858): The widget on which setState() or markNeedsBuild() was called was:
E/flutter (10858):   _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#43cf9](state: _OverlayEntryState#85a18)
E/flutter (10858): The widget which was currently being built when the offending call was made was:
E/flutter (10858):   OverlayBuilder(dirty, state: _OverlayBuilderState#2efb1)
E/flutter (10858): #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3449:11)
E/flutter (10858): #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3475:6)
E/flutter (10858): #2      State.setState (package:flutter/src/widgets/framework.dart:1141:14)
E/flutter (10858): #3      _OverlayEntryState._markNeedsBuild (package:flutter/src/widgets/overlay.dart:174:5)
E/flutter (10858): #4      OverlayEntry.markNeedsBuild (package:flutter/src/widgets/overlay.dart:149:24)
E/flutter (10858): #5      _OverlayBuilderState.buildOverlay (package:fluttery/src/layout_overlays.dart:158:19)
E/flutter (10858): <asynchronous suspension>
E/flutter (10858): #6      _OverlayBuilderState.build (package:fluttery/src/layout_overlays.dart:163:5)
E/flutter (10858): #7      StatefulElement.build (package:flutter/src/widgets/framework.dart:3743:27)
E/flutter (10858): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3655:15)
E/flutter (10858): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
E/flutter (10858): #10     StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
E/flutter (10858): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
E/flutter (10858): #12     _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:118:18)
E/flutter (10858): #13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2235:19)
E/flutter (10858): #14     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:107:11)
E/flutter (10858): #15     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1666:58)
E/flutter (10858): #16     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:735:15)
E/flutter (10858): #17     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1666:13)
E/flutter (10858): #18     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:205:5)
E/flutter (10858): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
E/flutter (10858): #20     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
E/flutter (10858): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
E/flutter (10858): #22     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
E/flutter (10858): #23     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:338:7)
E/flutter (10858): #24     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
E/flutter (10858): #25     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
E/flutter (10858): #26     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
E/flutter (10858): #27     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:704:18)
E/flutter (10858): #28     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
E/flutter (10858): #29     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
E/flutter (10858): #30     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/render
```

Flutter version: 
```
Flutter 0.5.6-pre.75 • channel master • https://github.com/flutter/flutter.git
Framework • revision 5e54b9e0fd (2 hours ago) • 2018-06-26 10:10:43 +0200
Engine • revision 549c855e89
Tools • Dart 2.0.0-dev.63.0.flutter-4c9689c1d2
```

**Comment by mayur-novus** [comment]
Probably an issue with fluttery package.
Specifically in the AnchoredOverlay class

**Comment by arrowoliver** [comment]
I am facing the same issue.

**Comment by JigneshPatel23** [comment]
Hi @mayur-novus I have tried on beta channel of flutter and it's working fine. 
Please try on beta channel for flutter.

**Comment by marciarocha** [comment]
The beta channel does not work for me

**Comment by koami** [comment]
> 
> 
> Probably an issue with `fluttery` package.
> Specifically in the `AnchoredOverlay` class

Yeah, Do you have an approach to solve it.?

**Comment by erfanjazebnikoo** [comment]
I replaced 
```dart
context.size
```
 with 
```dart
MediaQuery.of(context).size
```
This change resolves the first problem and the buttons work fine! But the new exception is:

```
I/flutter ( 6689): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 6689): The following assertion was thrown while rebuilding dirty elements:
I/flutter ( 6689): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3553 pos 12: '!_dirty': is not
I/flutter ( 6689): true.
I/flutter ( 6689): 
I/flutter ( 6689): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 6689): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 6689): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 6689):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 6689): 
I/flutter ( 6689): When the exception was thrown, this was the stack:
I/flutter ( 6689): #2      Element.rebuild (package:flutter/src/widgets/framework.dart:3553:12)
I/flutter ( 6689): #3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter ( 6689): #4      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
I/flutter ( 6689): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter ( 6689): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 6689): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 6689): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 6689): #9      _invoke (dart:ui/hooks.dart:154:13)
I/flutter ( 6689): #10     _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter ( 6689): (elided 2 frames from class _AssertionError)
I/flutter ( 6689): 
I/flutter ( 6689): The element being rebuilt at the time was index 0 of 2:
I/flutter ( 6689):   CardStack(dirty, state: _CardStackState#d7a8d)
I/flutter ( 6689): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

Flutter version:
```
    • Flutter version 1.0.0 at D:\Android\flutter
    • Framework revision 5391447fae (2 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
```

**Comment by olivoil** [comment]
Instead of making the `_slideLeft`, `_slideRight`, and `_slideUp` methods `async`, you can execute their content in [addPostFrameCallback](https://docs.flutter.io/flutter/scheduler/SchedulerBinding/addPostFrameCallback.html) so that they are processed after rendering.

It should look like this:

```dart
  void _slideRight() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final double screenWidth = context.size.width;
      dragStart = _chooseRandomDragStart();
      slideOutTween =
          Tween<Offset>(begin: cardOffset, end: Offset(2 * screenWidth, 0.0));
      slideOutAnimation.forward(from: 0.0);
    });
  }
```

**Comment by Feelthewind** [comment]
> Instead of making the `_slideLeft`, `_slideRight`, and `_slideUp` methods `async`, you can execute their content in [addPostFrameCallback](https://docs.flutter.io/flutter/scheduler/SchedulerBinding/addPostFrameCallback.html) so that they are processed after rendering.
> 
> It should look like this:
> 
> ```dart
>   void _slideRight() {
>     WidgetsBinding.instance.addPostFrameCallback((_) {
>       final double screenWidth = context.size.width;
>       dragStart = _chooseRandomDragStart();
>       slideOutTween =
>           Tween<Offset>(begin: cardOffset, end: Offset(2 * screenWidth, 0.0));
>       slideOutAnimation.forward(from: 0.0);
>     });
>   }
> ```



> Instead of making the `_slideLeft`, `_slideRight`, and `_slideUp` methods `async`, you can execute their content in [addPostFrameCallback](https://docs.flutter.io/flutter/scheduler/SchedulerBinding/addPostFrameCallback.html) so that they are processed after rendering.
> 
> It should look like this:
> 
> ```dart
>   void _slideRight() {
>     WidgetsBinding.instance.addPostFrameCallback((_) {
>       final double screenWidth = context.size.width;
>       dragStart = _chooseRandomDragStart();
>       slideOutTween =
>           Tween<Offset>(begin: cardOffset, end: Offset(2 * screenWidth, 0.0));
>       slideOutAnimation.forward(from: 0.0);
>     });
>   }
> ```

Do you have a working code for this app? It doesn't solve the problem.

[ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (19093): setState() or markNeedsBuild() called during build.
E/flutter (19093): This _OverlayEntry widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
E/flutter (19093): The widget on which setState() or markNeedsBuild() was called was:
E/flutter (19093):   _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#7246f](state: _OverlayEntryState#1ec42)
E/flutter (19093): The widget which was currently being built when the offending call was made was:

**Comment by dipendra-sharma** [comment]
This is because of Fluttery 0.0.8. 
I found a workaround. Try to change AnchoredOverlay.dart 

[https://github.com/matthew-carroll/fluttery/issues/4#issuecomment-459231202](url)

It's working for me.

**Comment by Mariog75** [comment]
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: Cannot get size during build.
The size of this render object has not yet been determined because the framework is still in the process of building widgets, which means the render tree for this frame has not yet been determined. The size getter should only be called from paint callbacks or interaction event handlers (e.g. gesture callbacks).

If you need some sizing information during build to decide which widgets to build, consider using a LayoutBuilder widget, which can tell you the layout constraints at a given location in the tree. See <https://api.flutter.dev/flutter/widgets/LayoutBuilder-class.html> for more details.

The size getter was called for the following element:
  DraggableCard
#0      Element.size.<anonymous closure> (package:flutter/src/widgets/framework.dart:3276:9)
#1      Element.size (package:flutter/src/widgets/framework.dart:3298:6)
#2      _DraggableCardState._slideRight (package:travl/cards.dart:286:33)
<asynchronous suspe<…>

Any fix?

**Comment by timothystone** [comment]
@Mariog75 did you try @olivoil fix here yet? https://github.com/matthew-carroll/flutter_ui_challenge_tinder_matching/issues/1#issuecomment-451603627

I was about too. Will provide feedback. I'm running ... 

```
    • Flutter version 1.7.8+hotfix.4 at /usr/local/flutter
    • Framework revision 20e59316b8 (6 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0
```

**Comment by timothystone** [comment]
The @olivoil fix worked for me! 👍 given. Though I'm reading @dipendra-sharma comment and wondering: I'm using `fluttery_dart2: 0.0.9` vs. `fluttery: 0.0.8` as well. I removed the `async` per the @olivoil note. The timing seems a bit jerky, but may be the simulator.

**Comment by timothystone** [comment]
@dipendra-sharma, it's not too dated, but you may want to send a PR to the `fluttery` repo. As it is, I have to compare and contrast your `.txt` attachment with the `fluttery 0.0.8` release by forking/cloning the repo and putting your change in. :/ Which is not too hard, but... :)
